platform :ios, '9.0'

target 'SkyApp' do
  use_frameworks!

  pod 'RxSwift', '~> 4.4.1'
  pod 'RxCocoa', '~> 4.4.1'

  target 'SkyAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SkyAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
